# Generated by Django 4.2.7 on 2023-11-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_about_product_image_product_description_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_3',
            new_name='description_2',
        ),
    ]
