# Generated by Django 4.2.7 on 2023-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Товар со скидкой?'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемые продукты'),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Товар новый (Новые поступления)?'),
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Товар популярный (трендовый)?'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
    ]
