# Generated by Django 4.2.7 on 2023-11-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_reviewproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduct',
            name='post',
            field=models.BooleanField(default=False, verbose_name='Выложить на сайт'),
        ),
    ]
