# Generated by Django 4.2.7 on 2023-12-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
