# Generated by Django 4.2.7 on 2023-12-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_about_descriptions_2_about_image_2_about_title_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='descriptions_2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_2',
        ),
    ]
