# Generated by Django 4.2.7 on 2023-12-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='clients_title',
            field=models.CharField(default='0', max_length=155, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='data',
            name='employees_title',
            field=models.CharField(default='0', max_length=155, verbose_name='кол-во сотрудников'),
        ),
        migrations.AddField(
            model_name='data',
            name='orders_title',
            field=models.CharField(default='0', max_length=155, verbose_name='кол-во заказов в месяц'),
        ),
        migrations.AddField(
            model_name='data',
            name='products_title',
            field=models.CharField(default='0', max_length=155, verbose_name='кол-во продуктов'),
        ),
        migrations.AlterField(
            model_name='data',
            name='clients',
            field=models.CharField(default='0', max_length=155, verbose_name='Введите значение'),
        ),
    ]
