# Generated by Django 4.2.7 on 2023-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_data_clients_title_data_employees_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='clients_title',
            field=models.CharField(max_length=155, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='data',
            name='employees',
            field=models.CharField(default='0', max_length=155, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='data',
            name='employees_title',
            field=models.CharField(max_length=155, verbose_name='Введите значение'),
        ),
        migrations.AlterField(
            model_name='data',
            name='orders',
            field=models.CharField(default='0', max_length=155, verbose_name='Введите значение'),
        ),
        migrations.AlterField(
            model_name='data',
            name='orders_title',
            field=models.CharField(max_length=155, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='data',
            name='products',
            field=models.CharField(default='0', max_length=155, verbose_name='Введите значение'),
        ),
        migrations.AlterField(
            model_name='data',
            name='products_title',
            field=models.CharField(max_length=155, verbose_name='Заголовок'),
        ),
    ]
