# Generated by Django 4.2.7 on 2024-01-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_data_clients_title_alter_data_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Имя пользователя')),
                ('phone', models.CharField(blank=True, max_length=155, null=True, verbose_name='Номер телефона')),
                ('fullinfo', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка на подбор ноутбука',
                'verbose_name_plural': 'Заявки на подбор ноутбука',
            },
        ),
    ]
