# Generated by Django 4.2.7 on 2024-01-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_chooselaptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chooselaptop',
            name='fullinfo',
            field=models.TextField(blank=True, null=True, verbose_name='Выбранные поля'),
        ),
    ]
